language: r
dist: xenial
addons:
  snaps:
    - hugo

branches:
  only:
    - master

cache:
  packages: yes

latex: false

script:
  - Rscript -e 'blogdown::build_site()'

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: public
  fqdn: travis-blogdown.yihui.name
